const BACKEND_URL="https://naya-tts-backend.vercel.app/api/generate";
const $=id=>document.getElementById(id);
let currentAudioUrl=null, imageBase64="", imageMimeType="";

document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');$(tab.dataset.tab).classList.add('active');}));
$('textInput')?.addEventListener('input',()=> $('characterCount').textContent=$('textInput').value.length);
$('generateButton')?.addEventListener('click',generateVoice);
$('uploadBox')?.addEventListener('click',()=> $('imageInput').click());
$('imageInput')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024)return showStatus('Ukuran gambar maksimal 10MB.');imageMimeType=f.type;const r=new FileReader();r.onload=()=>{imageBase64=r.result.split(',')[1];$('imagePreview').src=r.result;$('imagePreview').style.display='block';showStatus('Gambar siap diproses.');};r.readAsDataURL(f);});
$('generateImageButton')?.addEventListener('click',generateImagePrompt);
$('copyPromptButton')?.addEventListener('click',async()=>{await navigator.clipboard.writeText($('promptOutput').value);showStatus('Prompt berhasil disalin.');});
function showStatus(m){$('status').textContent=m;}
function setBusy(b,el,label){el.disabled=b;el.textContent=b?'Sedang memproses...':label;}
async function generateVoice(){const text=$('textInput').value.trim();if(!text)return showStatus('Teks narasi belum diisi.');setBusy(true,$('generateButton'),'▶ Generate MP3');showStatus('Menghubungi Gemini TTS...');try{const r=await fetch(BACKEND_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'tts',text:( $('styleInput').value.trim()||'Bacakan dengan suara natural dan ramah.')+'\n\nNarasi:\n'+text,voiceName:$('voiceSelect').value,speed:$('speedSelect').value})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'Gagal membuat audio');const blob=convertBase64PcmToMp3(d.audioBase64,24000,1);currentAudioUrl&&URL.revokeObjectURL(currentAudioUrl);currentAudioUrl=URL.createObjectURL(blob);$('audioPlayer').src=currentAudioUrl;$('audioPlayer').style.display='block';$('downloadButton').href=currentAudioUrl;$('downloadButton').download=(($('fileNameInput').value.trim()||'AnaAudio_01').replace(/[\\/:*?"<>|]/g,'')+'.mp3').replace('.mp3.mp3','.mp3');$('downloadButton').style.display='inline-block';showStatus('MP3 berhasil dibuat.');}catch(e){showStatus('Terjadi kesalahan: '+e.message);}finally{setBusy(false,$('generateButton'),'▶ Generate MP3');}}
async function generateImagePrompt(){if(!imageBase64)return showStatus('Silakan upload gambar terlebih dahulu.');const btn=$('generateImageButton');setBusy(true,btn,'▶ Generate Prompt Video Flow');showStatus('AI sedang membaca gambar dan membuat prompt...');try{const r=await fetch(BACKEND_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'image_prompt',imageBase64,mimeType:imageMimeType,videoType:$('imageStyle').value,duration:$('videoDuration').value,visualStyle:$('videoStyle').value,hook:$('hookInput').value,cta:$('ctaInput').value,language:$('imageLanguage').value,voiceName:$('imageVoice').value})});const d=await r.json();if(!r.ok||!d.success)throw Error(d.error||'Gagal membuat prompt');$('promptOutput').value=d.prompt||'';$('copyPromptButton').style.display='block';showStatus('Prompt video berhasil dibuat.');}catch(e){showStatus('Terjadi kesalahan: '+e.message);}finally{setBusy(false,btn,'▶ Generate Prompt Video Flow');}}
function convertBase64PcmToMp3(base64,sampleRate,channels){const b=atob(base64),u=new Uint8Array(b.length);for(let i=0;i<b.length;i++)u[i]=b.charCodeAt(i);const pcm=new Int16Array(u.buffer),enc=new lamejs.Mp3Encoder(channels,sampleRate,128),out=[];for(let i=0;i<pcm.length;i+=1152){const x=enc.encodeBuffer(pcm.subarray(i,i+1152));if(x.length)out.push(new Int8Array(x));}const f=enc.flush();if(f.length)out.push(new Int8Array(f));return new Blob(out,{type:'audio/mpeg'});}
